# Generated by Django 4.1.7 on 2023-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
                ('para4', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
